@startuml
!pragma layout smetana

class Main {
    + static void main(String[] args)
}

Main --> Netflix

class Netflix {

}

Netflix --> UserManager
UserManager --> Netflix



class UserManager {
    - HashMap<String, String> userData
    - String username

    + void createUser(String username, String password)
    + boolean validateUser(String username, String password)
}

Netflix --> Menu

class Menu {
    - String username
    + List<AllMedia> mediaList

    + void searchFilm()
    + void sortByCategory()
    + void watchedFilms()
    + void savedFilms()
    + List<saveAllData> searchMovies(String search)

    + List<String> saveMovieData(String path)
    + List<String> saveSeriesData(String path)
    + List<String> AllMedia(String path)
}

class FileIO extends UserManager {

    + HashMap<String, String> loadUserData(String path)
    + void saveUserData(HashMap<String, String>, String path)
}

abstract class Media extends Menu {
    + String title
    + String genre
    + int releaseYear
    + float rating


}

class Movie extends Media {
    + int duration
    + List<movies> readMovieData(String path)
}

class Series extends Media {
    + int episodes
    + int seasons
    + List<series> readSeriesData(String path)
}
@enduml
